import type { Metadata } from "next";
import {Montserrat} from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const montserrat =  Montserrat({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  display: 'swap',
}

)
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className}  antialiased w-full min-h-screen`}
      >
        <main className="w-full h-full">
        {children}

        </main>
      </body>
    </html>
  );
}
